print("Hello, World!")
print("This is a test script.")
print("Running test.py")
print("End of test.py")
print("All done!")
print("Goodbye!")
print("This is a simple Python script.")
print("Let's add some more functionality.")